### ISSUE TITLE
Show also remote branches in git merge

### ISSUE THREAD

**Issue by himhimlo** [vladimir-kotikov/clink-completions#103]
Now the git merge command auto complete with local branches instead of all branches. Will you consider change it to auto complete with all branches so that it behaves just like in bash environment? i.e. Changing from `"merge" .. parser({branches},` to `"merge" .. parser({local_or_remote_branches},` in `git.lua`.

**Comment by chrisant996** [comment]
This should be coming in the next release, probably within the next 2 weeks.

**Comment by chrisant996** [comment]
Closing because it is fixed in the dev branch, and closing it helps me keep track of the remaining work for the next release (which will include the dev changes).
