### ISSUE TITLE
Git prompt shouldn't replace path text

### ISSUE THREAD

**Issue by OfficerHalf** [vladimir-kotikov/clink-completions#104]
(Forgive me if this is the wrong place - I'm actually using Cmder, and I think I've tracked the issue back here.)

Small issue with the way git_prompt works. It looks like it can catch part of the path and replace that as well.
```
C:\dev -> originel\OfficerHalf.github.io (dev -> origin)
(ThreeSix) λ pwd
C:\devel\OfficerHalf.github.io
```

The `dev` in both the git branch and in the path are *both* being replaced with `dev -> origin`.

**Comment by lucas-gonzalez** [comment]
I have had the same issue and backtracked it to [git_prompt.lua#L81](https://github.com/vladimir-kotikov/clink-completions/blob/master/git_prompt.lua#L81) and [git_prompt.lua#L83](https://github.com/vladimir-kotikov/clink-completions/blob/master/git_prompt.lua#L83). Both `gsub` invocations are replacing all instances of the current branch name in the `prompt.value`.
