### ISSUE TITLE
Add completion for 'elevate'

### ISSUE THREAD

**Issue by ATiltedTree** [vladimir-kotikov/clink-completions#105]
Elevate is a sudo for Windows
https://github.com/jnm2/Elevate
I would do it myself but I am not that good at lua.
It is very simple :
	Just show every completion after elevate.exe

**Comment by chrisant996** [comment]
In 2019 there wasn't a way.  But in more recent versions of Clink now the following is possible:

**elevate.lua**
```lua
clink.argmatcher('elevate'):chaincommand()
```
