### ISSUE TITLE
Add CONTRIBUTORS and LICENSE

### ISSUE THREAD

**Issue by vladimir-kotikov** [vladimir-kotikov/clink-completions#11]
- [x] add licence information (added in https://github.com/vladimir-kotikov/clink-completions/commit/d23bbfd625c09a06a765ca28e1b285be52f39fe0)
- [x] add information for contributors
- [x] add CHANGELOG

**Comment by vladimir-kotikov** [comment]
License is added in https://github.com/vladimir-kotikov/clink-completions/commit/d23bbfd625c09a06a765ca28e1b285be52f39fe0

**Comment by chrisant996** [comment]
Closing this since #26 tracks adding information for contributors.
