### ISSUE TITLE
Add autocompletion for path-globs

### ISSUE THREAD

**Issue by djwashburn** [vladimir-kotikov/clink-completions#115]
See this https://stackoverflow.com/a/31789441/1033203. If I'm in a project with a deep directory structure, like a large java project, and I want to say `git add` a file, it would be nice to type `git add **/SignPr*<tab>` and have it autocomplete to `git add /really/long/path/SignPresenter.java` . This does not seem to work for me at the moment (based on using Cmder on Windows 10, which I understand relies on clink-completions for autocomplete functionality.)

**Comment by chrisant996** [comment]
There are several problems with completing `**/SignPr*`.  One is that it could take a few minutes to collect matches, depending on where it is used.  Another is that there isn't a good way to show matches from multiple different directories.  There are several other issues as well.

But #116 sounds like it would be a different (and much easier) way of addressing the motivation behind your request.

You could also try using [fzf](https://github.com/junegunn/fzf) and [clink_fzf](https://github.com/chrisant996/clink-fzf) and using `git add **`<kbd>Tab</kbd> and then type `signpr` and fzf would filter the list to matching files.

**Comment by chrisant996** [comment]
Closing as a duplication of #116.
