### ISSUE TITLE
Only include changed files in `git checkout` completion

### ISSUE THREAD

**Issue by youngmit** [vladimir-kotikov/clink-completions#116]
Right now, when adding filenames to the `git checkout` completions, all files are included. Usually one is only interested in checking out a file that is tracked by the repository and changed (essentially the output of `git ls-files -c`, plus maybe some other things that I'm not thinking of). This is at least how oh-my-zsh does it. As it is, so many files are included in the completion that I've just turned it off as too noisy.

Is there any way to only include files that are tracked/changed? I spent a little time trying it myself, only to find that most of the other git completions are implemented by looking at `refs/...`, rather than asking git. I don't know how to do Lua really, but haven't found a way to execute an external program and consume its standard output sanely. Any ideas?

**Comment by youngmit** [comment]
I guess I am blind, and missed the `io.popen` stuff that also gets used for git aliases. I was able to make something work for listing files. Do people think that this is useful behavior? Should I put together a PR?

**Comment by chrisant996** [comment]
@youngmit That sounds interesting.  I would appreciate if you could share a PR.  Branches and changed files makes sense.

**Comment by chrisant996** [comment]
> essentially the output of `git ls-files -c`

I think that was a typo and `git ls-files -m` was meant.

For `git checkout` and `git add` deleted files should be included.
For `git add` untracked files should be included.

So I think `git status` is the query for `git add`.
And I think maybe filtering the results from `git status` is the query for `git checkout`.

It gets interesting how to list the matches...
Should `git add f` list `foo\` or `foo\sub\sub\sub\sub\sub\super\deep\etc\bar.cpp` as matches?
I suppose full relative paths, at least for now.

**Comment by chrisant996** [comment]
Closing because it is added in the dev branch, and closing it helps me keep track of the remaining work for the next release (which will include the dev changes).
