### ISSUE TITLE
.init.lua isn't loaded under some circumstances

### ISSUE THREAD

**Issue by vladimir-kotikov** [vladimir-kotikov/clink-completions#117]
See https://github.com/cmderdev/cmder/issues/957 and https://github.com/cmderdev/cmder/issues/957#issuecomment-535692572 for background

> Basically `.init.lua` is the root cause here as it modifies modules path so other modules can be loaded and I believe it just needs to be renamed into something else to not start with the dot (perhaps underscore should work, it just needs to be a symbol that goes before other ASCII symbols so that this module gets executed first by Clink)

**Comment by vladimir-kotikov** [comment]
Also https://github.com/cmderdev/cmder/pull/2278

**Comment by chrisant996** [comment]
I'll rename the file.  This should be coming in the next release, probably within the next 2 weeks.

**Comment by chrisant996** [comment]
Closing because it is fixed in the dev branch, and closing it helps me keep track of the remaining work for the next release (which will include the dev changes).
