### ISSUE TITLE
How to write a custom matcher that can traverse folders with specific filename pattern?

### ISSUE THREAD

**Issue by doggy8088** [vladimir-kotikov/clink-completions#121]
I have a CLI command like this:

```sh
 dotnet publish [options] <PROJECT | SOLUTION>
```

The last part of the command is a file. The file can be current folder, parent folder or some other folders. I don't know how to write a matcher to filter files.

I tried below, but this filter files only in current folder:

```lua
local csproj_files_matcher = matchers.create_files_matcher("*.csproj")
```

If I try to write `dotnet publish ..\` then hit `Tab`, then no suggestion will be shown.

How can I write this?

**Comment by vladimir-kotikov** [comment]
It's hard to tell exactly how you would do this, but looks like you can implement a hybrid of [`matchers.files`](https://github.com/vladimir-kotikov/clink-completions/blob/08755a32c121921226a09f365ed08a6ee3c2f4de/modules/matchers.lua#L36) and [`matchers.create_file_matcher`](https://github.com/vladimir-kotikov/clink-completions/blob/08755a32c121921226a09f365ed08a6ee3c2f4de/modules/matchers.lua#L70) - basically you need the factory that will take a filename pattern (like `*.csproj`) and return a modified version of `matchers.files` that use the provided pattern instead of default `*` [here](https://github.com/vladimir-kotikov/clink-completions/blob/08755a32c121921226a09f365ed08a6ee3c2f4de/modules/matchers.lua#L45)

**Comment by vladimir-kotikov** [comment]
Feel free to make a PR if you figure out how to do this - this is going to be a nice addition

**Comment by doggy8088** [comment]
@vladimir-kotikov I'm still figuring out how to make it. 

I found this sample: https://gist.github.com/PeterJCLaw/8359fb02f2be5b94f9d2

What is `clink.register_match_generator`? How can I use it?

**Comment by vladimir-kotikov** [comment]
I haven't touched this code for like 5 years so it's hard for me to figure out. I'd do this just like I told in my previous comment but if you would like to use this snippet - I think you'll need to do some experimentation by your own.

**Comment by doggy8088** [comment]
@vladimir-kotikov I made it!! 😄

```lua

exports.ext_files = function (extension)
    return function (word)

        -- Strip off any path components that may be on text.
        local prefix = ""
        local i = word:find("[\\/:][^\\/:]*$")
        if i then
            prefix = word:sub(1, i)
        end

        -- dir matches.
        local dirmatches = w(clink.find_dirs(word.."*", true))
        :filter(function (dir)
            return clink.is_match(word, prefix..dir) and
                (include_dots or path.is_real_dir(dir))
        end)
        :map(function(dir)
            return prefix..dir
        end)

        -- extension matches. (e.g. *.dll)
        local dllmatches = w(clink.find_files(word..extension, true))
        :filter(function (file)
            return clink.is_match(word, prefix..file)
        end)
        :map(function(file)
            return prefix..file
        end)
        
        -- concat two tables
        -- https://stackoverflow.com/questions/1410862/concatenation-of-tables-in-lua
        for _,v in ipairs(dirmatches) do 
            table.insert(dllmatches, v)
        end

        -- Tell readline that matches are files and it will do magic.
        if #dllmatches ~= 0 then
            clink.matches_are_files()
        end

        return dllmatches
    end
end
```

**Comment by chrisant996** [comment]
I don't plan to merge this PR, because with Clink v1.0 and higher it's much simpler, and also automatically .

```lua
local function csproj_files(word) return clink.filematches(word.."*.csproj") end
local function sln_files(word) return clink.filematches(word.."*.sln") end
    
clink.argmatcher("program"):addarg(csproj_files, sln_files, clink.dirmatches)
```

And then completion coloring works properly and efficiently, as well.

**Comment by chrisant996** [comment]
On second thought, maybe I'll merge it and also make it use the enhanced approach on newer versions of Clink.

**Comment by chrisant996** [comment]
This is also updated to use new APIs when available.
