### ISSUE TITLE
Feature: Same as zsh-autosuggestions

### ISSUE THREAD

**Issue by Daniel-Mendes** [vladimir-kotikov/clink-completions#127]
### Purpose of the issue
- [ ] Bug report (encountered problems/errors)
- [x] Feature request (request for new functionality)
- [x] Question

### Version Information

- Cmder 1.3.14.982

- Windows 10 Home 2004

### Description of the issue

Is there a plugin to add auto-suggestions like [zsh-autosuggestions](https://github.com/zsh-users/zsh-autosuggestions). I know there is a tab-completion but I really want the auto-suggestion to be displayed.

**Screenshot** (Ubuntu WSL with Oh my ZSH with plugin zsh-autosuggestions) :
![image](https://user-images.githubusercontent.com/28825568/79635255-37295f80-8170-11ea-9aba-496cce9fab53.png)

**Comment by kamenminkov** [comment]
It's possible already, just do `clink set autosuggest.enable true`.
