### ISSUE TITLE
Completion script for Makefiles?

### ISSUE THREAD

**Issue by DaelonSuzuka** [vladimir-kotikov/clink-completions#128]
Is it possible to make a completion script that will scan for Makefile targets and provide autocompletion for them? I've tried reading the Clink docs and some of the scripts in this repo, but I don't know enough Lua to make heads or tails of it.

If somebody who knows how clink/lua work can tell me if the idea is even reasonable, I'd really appreciate it.

**Comment by chrisant996** [comment]
@DaelonSuzuka it's possible.  It's a matter of making a parser for makefiles, to extract the targets.  The Lua part is straightforward.  Building logic for parsing makefiles reliably is where most of the effort would go.

I don't want to do that myself, but I would be happy to answer questions about Lua and Clink, to help someone else do it.
