### ISSUE TITLE
[Feature Request] Auto completion for git commands when using alias

### ISSUE THREAD

**Issue by ovasquez** [vladimir-kotikov/clink-completions#140]
### Description
The idea of this feature is to provide auto completion when using aliases for git commands, for example:

#### Current behavior
```
$ git checkout <Press TAB, auto completions shows branches>
$ git config --global alias.co checkout
$ git co <Press TAB, no branches are shown>
```
#### Expected behavior
```
$ git checkout <Press TAB, auto completions shows branches>
$ git config --global alias.co checkout
$ git co <Press TAB, auto completions shows branches>
```

I have been looking at the code and would be willing to give it a try but I have zero experience with Lua, so if someone could provide guidance on this that would be appreciated.

### Related issues in other repos
Just to reference them so they can be updated if/when this feature is added.
- https://github.com/chrisant996/clink/issues/83
- https://github.com/cmderdev/cmder/issues/1495
- https://github.com/mridgers/clink/issues/517

**Comment by chrisant996** [comment]
I believe I've implemented this in PR #149.  Hopefully @vladimir-kotikov can review the PR soon.

**Comment by chrisant996** [comment]
This should be coming in the next release, probably within the next 2 weeks.

**Comment by chrisant996** [comment]
Closing because #149 has been merged. There is some more work to do before the next release is ready, though.
