### ISSUE TITLE
Add autocompletion for sudo

### ISSUE THREAD

**Issue by kamenminkov** [vladimir-kotikov/clink-completions#145]
It would be nice to have completions for [sudo](https://github.com/lukesampson/psutils) - it's a PowerShell script somewhat mimicking what `sudo` does on UNIX-like systems (shows UAC prompt if you have that set up, but executes commands as admin without a prompt if the UAC prompt is disabled - so it's handy for executing commands in place with elevated privileges without having to open the shell in an elevated window).

Functionally I see this done in a pass-through approach of some way; any suggestions shown after `sudo` should function the same way as if no `sudo` was entered. I can't think of any edge cases.

Way to reproduce:

`sudo scoop update autohotkey`

Expected result: after entering `sudo scoop u`, suggestions should kick in and show `update` (the same way as when you enter just `scoop u`); same thing for other commands supported by completions.

Actual result: entering `sudo scoop u`, the `u` gets expanded into subdirectories starting with "u" that happen to be in the CWD but not into the `update` subcommand of `scoop`.

**Comment by kamenminkov** [comment]
Oh, cool, didn't know that. Thank you!

**Comment by chrisant996** [comment]
It's easy to add a sudo completion script.  But there are several different sudo implementations for Windows, and different ones have different flags.  I'm exploring some options for what's the best way to add this.

**Comment by chrisant996** [comment]
Closing because it is fixed in the dev branch, and closing it helps me keep track of the remaining work for the next release (which will include the dev changes).

**Comment by kamenminkov** [comment]
It'd be nice to have it by default indeed. Thank you!

**Comment by chrisant996** [comment]
I made a native C++ `sudo` for Windows, available at [sudo-windows](https://github.com/chrisant996/sudo-windows).

I'll extend the `sudo.lua` argmatcher to be able to recognize when that variation of sudo is used, and show its available flags as well.

**Comment by kamenminkov** [comment]
Nice! Do you plan on making it available through Scoop?

**Comment by chrisant996** [comment]
> Nice! Do you plan on making it available through Scoop?

Anyone can make it available through scoop.  I can take a look, though.

However, since scoop uses batch script shims (I don't understand why), the way that batch script parse command lines can interfere with some command lines (for example, commas or equal signs or quotes etc).  So that will sometimes interfere with usage of sudo.

**Comment by chrisant996** [comment]
There's another complication -- x86 versus x64 (and eventually arm64).  Dealing with complexities of automatic multi-platform support on the same machine is something that involves a bunch of extra complexity (x64 machines should use x64 or x86 depending on the current context).

I suppose I could publish scoop for only x64 or for only x86, but either of those will malfunction in subtle ways in some cases on x64 machines, and x64 won't work at all on x86 machines.

So, making it available through scoop really involves solving other things as well.

Eventually, perhaps.

**Comment by kamenminkov** [comment]
Cool, thanks for the explanation.

**Comment by chrisant996** [comment]
It looks like scoop has a way to allow installing x64 or x86 depending on the machine architecture.  Not a perfect solution, but good enough.

**Comment by chrisant996** [comment]
[gsudo](https://github.com/gerardog/gsudo) is another sudo for Windows.  There are pros/cons between gsudo and the sudo-windows I published, but I'm quite happy to let gsudo be the preferred sudo for Windows, and gsudo is already on Scoop.  So I will not add sudo-windows to Scoop.

And I've added `gsudo` completions to clink-completions.
