### ISSUE TITLE
Git checkout -b should only autocomplete branch names

### ISSUE THREAD

**Issue by eblis** [vladimir-kotikov/clink-completions#150]
I think the `git checkout -b` command should only autocomplete branch names, it shouldn't list files in that case

**Comment by chrisant996** [comment]
The https://github.com/chrisant996/clink-completions fork and PR #149 include a fix for that: `-b` doesn't list completions at all -- it's a new branch name, so completion seems a bit nonsensical.

**Comment by chrisant996** [comment]
This will be fixed in the next release, probably within a week or two.

**Comment by chrisant996** [comment]
Closing because #149 has been merged. There is some more work to do before the next release is ready, though.
