### ISSUE TITLE
adb.lua misbehaving

### ISSUE THREAD

**Issue by mrplumber** [vladimir-kotikov/clink-completions#157]
clink-completions 0.4.0 (installed via scoop)
adb completion fails.
Please, see attached screenshot of console window:
![image](https://user-images.githubusercontent.com/15611917/187262644-f74b88ba-d1bb-43fc-a78a-8d45ac191240.png)
fastboot and scrcpy as well.
Some other completions I have tried seem to work properly.

**Comment by chrisant996** [comment]
Thanks for reporting it!
