### ISSUE TITLE
fastboot.lua and scrcpy.lua misbehaving too

### ISSUE THREAD

**Issue by mrplumber** [vladimir-kotikov/clink-completions#158]
Commit [1e3adbe](https://github.com/vladimir-kotikov/clink-completions/commit/1e3adbe2c38bf0f2e11048e7a7cd1407549c31ec) only fixes adb.lua although similar issue is also relevant to fastboot.lua and scrcpy.lua:
![image](https://user-images.githubusercontent.com/15611917/187278691-5d2812dc-aab2-4bef-8934-ffdcb0fbb1ad.png)

**Comment by chrisant996** [comment]
Confirmed, thanks.
