### ISSUE TITLE
Run git pull on script folders after update

### ISSUE THREAD

**Issue by binyaminyblatt** [vladimir-kotikov/clink-completions#161]
Just like clink itself needs to be kept up to date scripts do too and it would be really nice to either have a command that would update the script folders a script that would do it or even have it run automatically after an update

I'm not sure if I'm opening this request on the right repository it might make more sense for it to be a part of clink itself but I figure a script could run on startup or any other time I might choose

**Comment by chrisant996** [comment]
@binyaminyblatt I understand wanting to stay up to date. Why not write a script to do the updates that you want? Look for "clink_start.cmd" in the documentation.

I don't think Clink should build in an assumption that script directories use git, or that people always want git directories updated, or that starting CMD should wait for multiple git commands and network operations. It's already very easy for users to write a script to do that if they want.

**Comment by binyaminyblatt** [comment]
Is it possible to access the list of folders from the start up script

**Comment by chrisant996** [comment]
> Is it possible to access the list of folders from the start up script

`clink info`
