### ISSUE TITLE
openssl.lua:1179: attempt to compare number with string

### ISSUE THREAD

**Issue by mrplumber** [vladimir-kotikov/clink-completions#165]
Every time I type in any first character after command `openssl` (and period) message shows up:
```
❯ openssl p
coroutine failed:
...p\apps\clink-completions\current\completions\openssl.lua:1179: attempt to compare number with string
```

My setup is as follows:

```
❯ scoop list clink*
Installed apps matching 'clink*':

Name              Version Source Updated             Info
----              ------- ------ -------             ----
clink             1.4.12  main   2023-01-21 13:58:01 Global install
clink-completions 0.4.4   main   2023-01-16 20:52:14 Global install
clink-flex-prompt 0.11    main   2022-09-22 00:00:37 Global install
```

**Comment by chrisant996** [comment]
@mrplumber Thanks for reporting this!  It should be fixed now.

I'll publish a new release after the `winget` completions are updated with new flags; probably tonight or tomorrow.

I see you're using scoop, so in the meantime you can manually download the updated `completions\openssl.lua` script.
