### ISSUE TITLE
Error "module 'path' not found" on fresh install.

### ISSUE THREAD

**Issue by AqilCont** [vladimir-kotikov/clink-completions#166]
```cmd
d:\projects>git.exe
word classifier failed:
C:\Users\aqilc\AppData\Local\clink\completions\git.lua:3: module 'path' not found:
        no field package.preload['path']
        no file 'C:\Program Files (x86)\Lua\5.1\lua\path.luac'
        no file 'C:\WINDOWS\System32\path.dll'
        no file 'C:\WINDOWS\System32\loadall.dll'
        no file '.\path.dll'
stack traceback:
        [C]: in function 'require'
        C:\Users\aqilc\AppData\Local\clink\completions\git.lua:3: in main chunk
        [C]: in function 'dofile'
        {arguments.lua}: in function '?'
        {arguments.lua}: in function '?'
        {arguments.lua}: in function '?'
        {arguments.lua}: in function 'classify'
        {classifier.lua}: in function <{classifier.lua}:63>
        [C]: in function 'xpcall'
        {classifier.lua}: in function <{classifier.lua}:62>
            git
word classifier failed:
C:\Users\aqilc\AppData\Local\clink\completions\git.lua:3: module 'path' not found:
        no field package.preload['path']
        no file 'C:\Program Files (x86)\Lua\5.1\lua\path.luac'
        no file 'C:\WINDOWS\System32\path.dll'
        no file 'C:\WINDOWS\System32\loadall.dll'
        no file '.\path.dll'
stack traceback:
        [C]: in function 'require'
        C:\Users\aqilc\AppData\Local\clink\completions\git.lua:3: in main chunk
        [C]: in function 'dofile'
        {arguments.lua}: in function '?'
        {arguments.lua}: in function '?'
        {arguments.lua}: in function '?'
        {arguments.lua}: in function 'classify'
        {classifier.lua}: in function <{classifier.lua}:63>
        [C]: in function 'xpcall'
        {classifier.lua}: in function <{classifier.lua}:62>
            git
```

![image](https://user-images.githubusercontent.com/32044067/221050206-7b5100d2-faf0-41e9-aaeb-112622f003ff.png)

**Comment by chrisant996** [comment]
@AqilCont How did you install?

It looks like you're missing the scripts from the `modules\` directory. And possibly also from the `completions\` directory.

**Comment by AqilCont** [comment]
I installed `clink` today by using the setup.exe file in Releases to `C:\Programs\`. I installed `clink-completions` by using `git clone https://github.com/vladimir-kotikov/clink-completions.git completions` in the `%Appdata%/clink` directory.

**Comment by chrisant996** [comment]
> I installed `clink` today by using the setup.exe file in Releases to `C:\Programs\`. I installed `clink-completions` by using `git clone https://github.com/vladimir-kotikov/clink-completions.git completions` in the `%Appdata%/clink` directory.

Ah, I see.  The subdirectory name `completions\` is reserved in Clink, similar to how it is reserved in many other shells.  See [Completion directories](https://chrisant996.github.io/clink/clink.html#completion-directories) for details.

Rename `completions\` to something else.  I'll add a note in the Readme to help avoid future similar mishaps.

Also, it looks like step 3 from the installation steps may have been missed, as well:

3. Tell Clink to load scripts from the repo via `clink installscripts local_directory`.

For _local_directory_ substitute the fully qualified path to the clink-completions repro directory.

**Comment by AqilCont** [comment]
Oh sorry, I had done the 3rd step but forgot to mention it, thru this: `clink installscripts completions\`
Yeah maybe that should be pointed out somewhere.

I tried it again but with a different folder. There seemed to be no errors running it! The thing is that I don't know what to expect but it was the exact same experience using something like git inside a git directory and outside it, so I don't know if it's running properly yet.

All of these ran successfully:
```
cd C:\Users\aqilc\AppData\Local\clink
git clone https://github.com/vladimir-kotikov/clink-completions comp
clink installscripts comp\
```

**Comment by chrisant996** [comment]
How do you expect it to behave outside of a git directory?

You can invoke `git` outside of a git directory.  For example, `git clone` is typically invoked from outside a git directory.

Completions help you type things that can be predicted.  For example, inside a git directory, you'll see different completions for an argument to `git checkout` than when outside a git directory.

**Comment by chrisant996** [comment]
> I had done the 3rd step but forgot to mention it, thru this: `clink installscripts completions\` 

That adds a _relative_ path "completions\".  So whatever your current working directory is, it will try to find completion scripts in a "completions\" subdirectory, while you type commands.  Adding a relative path won't have the effect of specifying the specific  full path to the clink-completions repo.

I added text to emphasize that relative paths won't have the desired effect.  It didn't occur to me that it needed to be emphasized.

**Comment by AqilCont** [comment]
Ah, sorry maybe I should read a bit more of your site. There was just a lot so I skimmed through it and checked out a couple add-ons I could try out. I must've missed the details on how `installscripts` works, I thought it would "install" a path by resolving it to an absoulte directory first. This misunderstanding seems to explain my problems of why it still wasn't working.

Thank you for your guidance! It seems to work now, throughout every directory :D

**Comment by chrisant996** [comment]
> Ah, sorry maybe I should read a bit more of your site. There was just a lot so I skimmed through it and checked out a couple add-ons I could try out. I must've missed the details on how `installscripts` works, 

I appreciate that you're willing to accept some responsibility for the misunderstanding.  But I think the primary fault lies in the README text, which didn't have enough detail, and could accidentally steer some users into a mistake.  Hopefully the updated text won't steer people wrong anymore.

> I thought it would "install" a path by resolving it to an absoulte directory first. This misunderstanding seems to explain my problems of why it still wasn't working.

[Here](https://github.com/chrisant996/clink/issues/355#issuecomment-1262964584) is a thread discussing relative versus absolute paths in `clink installscripts`.

> Thank you for your guidance! It seems to work now, throughout every directory :D

Excellent.  :)
