### ISSUE TITLE
RFE: add completions for ping 

### ISSUE THREAD

**Issue by maximunited** [vladimir-kotikov/clink-completions#174]
Please add support for completions for the `ping` command.
1, all the command options (eg. `-t`, `-a`, `-i TTL`, `-l <buffer_size>`, etc..)
2. complete host names from hosts file. Extended: Get the host names/IPs from ssh completion

**Comment by chrisant996** [comment]
> Extended: Get the host names/IPs from ssh completion

Can you clarify this part?  The completion in [ssh.lua](https://github.com/vladimir-kotikov/clink-completions/blob/master/ssh.lua) lists hosts from `%USERPROFILE%\.ssh\config` and `%USERPROFILE%\.ssh\known_hosts` files.   That's what the "Extended" request is for, right?

**Comment by chrisant996** [comment]
From the `hosts` file, do you want both the IP and the mapped host names listed?

```
12.34.56.78    everything.everywhere.net
```

Which (or both) should that list as completions?
- [ ] `12.34.56.78`
- [ ] `everything.everywhere.net`

**Comment by maximunited** [comment]
> > Extended: Get the host names/IPs from ssh completion
> 
> Can you clarify this part? The completion in [ssh.lua](https://github.com/vladimir-kotikov/clink-completions/blob/master/ssh.lua) lists hosts from `%USERPROFILE%\.ssh\config` and `%USERPROFILE%\.ssh\known_hosts` files. That's what the "Extended" request is for, right?

Correct. Use ssh host completion for ping (if available)



> From the `hosts` file, do you want both the IP and the mapped host names listed?
> 
> ```
> 12.34.56.78    everything.everywhere.net
> ```
> 
> Which (or both) should that list as completions?
> 
> * [ ]  `12.34.56.78`
> * [ ]  `everything.everywhere.net`

Both please

**Comment by chrisant996** [comment]
> Both please

Cool -- I already added them and pushed the commit earlier today.
I'll publish a new release soon, but in the meantime you could either pull the repo or copy just the `completions\ping.lua` file.

**Comment by maximunited** [comment]
Pulled, already see a bugs, so reporting here.
I have some entries commentted out.
So it completes as `ping #`

The other issue is from ssh. In my `known_hosts` I have entries for non default port, they appear as:
```
[192.168.1.222]:26 ssh-rsa <really-long-string-here>
```
So completion is showing as:
`ping [192.168.1.222 `

I'll open a new issue on #2, since the same happens in ssh completion

**Comment by chrisant996** [comment]
> I have some entries commentted out. So it completes as `ping #`

Ok, thanks for reporting the problem.

I think you mean your `hosts` file has commented lines, the commented lines start with `#`, and the comment lines in the `hosts` file are turning into `#` completions.

Am I understanding correctly?

**Comment by chrisant996** [comment]
No, my first guess isn't possible.

Sharing examples would help me tremendously.

My next guess is that you mean you have lines like this in your hosts file:
`12.34.56.78  name  # this is a comment`

And that not only do `12.34.56.78` and `name` show up as completions, but also `#` and `this` and `is` and `a` and `comment` show up as completions.

Am I understanding correctly?

Please share specific examples, if I haven't understood yet.

**Comment by maximunited** [comment]
This is the hosts file I have:
```
# Copyright (c) 1993-2009 Microsoft Corp.
#
# This is a sample HOSTS file used by Microsoft TCP/IP for Windows.
#
# This file contains the mappings of IP addresses to host names. Each
# entry should be kept on an individual line. The IP address should
# be placed in the first column followed by the corresponding host name.
# The IP address and the host name should be separated by at least one
# space.
#
# Additionally, comments (such as these) may be inserted on individual
# lines or following the machine name denoted by a '#' symbol.
#
# For example:
#
# localhost name resolution is handled within DNS itself.
### setups ###
##########
# Geo7 #
##########
##########
# Geo6 #
##########
## OLD IP. Changed on 31/01/2021 ## 11.22.33.44     hani han ha143 ha-143
###########
# Geo5 #
###########
# GEO4
# GEO3
#######
# GEO2 #
#######
###########
# Geo1 #
###########
# Temp
###############
### DEV R&D ###
###############
# 102.54.94.97   rhino.acme.com                     # source server
# 38.25.63.10    x.acme.com                         # x client host
# 127.0.0.1      localhost
# ::1            localhost
# 5.5.152.11    jer j152
# 5.5.216.11    md mad m216
# 5.7.224.130  bag
# 5.7.239.194  nwy nyc ny nw nw112 nw-112
# 5.7.13.130   toro tor to147 to-147
# 150.7.247.130 to tok to807 to-807             # OLD 10.11.19.2
# 5.9.15.67    he hel                       # estcco005
# 10.94.44.135   me mex me141bc me141-bc
  10.151.71.49   tita
# 10.41.1.17     lan
  192.178.166.50   bou bur                     # RM20
```
It's much longer, but a lot of commented out lines

**Comment by chrisant996** [comment]
> ```
>   192.178.166.50   bou bur                     # MR20
> ```

Ah yes, thanks, there we go. That's the line doing it. Not the lines starting with a comment.

Great, a fix for this is coming.

**Comment by chrisant996** [comment]
Completed in 7a6e0559e25d7fcd877f64c49539c08d281f6aa6 in June 2023.
