### ISSUE TITLE
How to let 'git add' completion non-recursive

### ISSUE THREAD

**Issue by HiFiPhile** [vladimir-kotikov/clink-completions#178]
Hi,

Currently I'm on 0afbe630105a56c1ca6ecef85802f85422e2313d, when I type `git add` it lists all files recursively in the folder, which makes the output flooded.

Anyway to limit the completion to current folder, like `bash-completion` did ?

**Comment by chrisant996** [comment]
`git status` is recursive.  It's possible to rewrite the match generator to counteract that, but there are some benefits to the way it's currently behaving.  And while `bash-completion` might not list them recursively, some other completion libraries do list them recursively, so it seems that both ways are desirable to different people.

Can I ask some questions to help me better understand the scenario, and explore some possibilities that might be useful?

- Can you describe more about "makes the output flooded"?  How many files are listed?  Is it 100 or less?  Does it make the screen scroll?
- What key did you press after `git add `, and what command is it bound to?  Did you press <kbd>Tab</kbd>, and is Tab bound to `complete`?
- If so, would you be interested in configuring [`completion-query-items`](https://chrisant996.github.io/clink/clink.html#configcompletionqueryitems) or [`completion-auto-query-items`](https://chrisant996.github.io/clink/clink.html#configcompletionautoqueryitems) in the .inputrc file to prompt first before listing the completions?  For my own use, I have them set to `50` and `on`, respectively.
- Would configuring [`page-completions`](https://chrisant996.github.io/clink/clink.html#configpagecompletions) in the .inputrc file help?  It's `on` by default, so when a lot of completions are listed it should at least be pausing at each screenful, unless that's been overridden.

**Comment by HiFiPhile** [comment]
> Can you describe more about "makes the output flooded"? How many files are listed? Is it 100 or less? Does it make the screen scroll?

I'm working on a middle sized project with about 150 `.c` files, it makes the output scroll.
```
e:\code\Z3GatewayHost>git add
Display all 453 possibilities? (y or n)
```
Of cause I should add build output to `.gitignore`, which reduce the output to less than 50.

> What key did you press after git add , and what command is it bound to? Did you press Tab, and is Tab bound to complete?

I pressed `Tab`, I didn't change `Tab` behavior in `.inputrc`, I think it's `complete` by default.

> would you be interested in configuring [completion-query-items](https://chrisant996.github.io/clink/clink.html#configcompletionqueryitems) or [completion-auto-query-items](https://chrisant996.github.io/clink/clink.html#configcompletionautoqueryitems) in the .inputrc file to prompt first before listing the completions

I've `completion-auto-query-items on`, indeed it helped a lot. 

> Would configuring [page-completions](https://chrisant996.github.io/clink/clink.html#configpagecompletions) in the .inputrc file help?

I've it set to `on`. The built-in pager of `Display all * possibilities` is not so useful as it can only go down line by line with `Enter` key, same for `bash` but seems nobody willing to work on it https://bugs.launchpad.net/ubuntu/+source/bash/+bug/1691314

**Comment by chrisant996** [comment]
> Of cause I should add build output to `.gitignore`, which reduce the output to less than 50.

Yes.  That's important regardless of how completions are listed.

> The built-in pager of `Display all * possibilities` is not so useful as it can only go down line by line with `Enter` key, same for `bash`

In the pager, <kbd>Enter</kbd> goes by line and <kbd>Space</kbd> goes by page.  Also <kbd>d</kbd> goes by half-page.

> but seems nobody willing to work on it https://bugs.launchpad.net/ubuntu/+source/bash/+bug/1691314

Has anyone actually contacted the bash maintainer to suggest the ability to page into `less`?  The cited post is a complaint posted in a random spot on the internet.  Complaining into the ether isn't the same as sending a suggestion directly to an author.

**Comment by chrisant996** [comment]
Also, the `clink-select-complete` command displays an interactive scrollable and filter-able list to choose from.  And using [fzf](https://github.com/junegunn/fzf) (and the fzf integration script in [clink-gizmos](https://github.com/chrisant996/clink-gizmos)) can use fzf for another kind of interactive scrollable and fuzzy filtered list to choose from.

These all seem like even more functional and convenient solutions than removing the recursive list.  Do any of these alternatives seem helpful?  Do you still want recursion to be removed?

If you still want it removed, then I can add a setting to configure it that way, but I want it on by default.

**Comment by HiFiPhile** [comment]
> In the pager, Enter goes by line, Space or Tab go by page, and d goes by half-page.

Thanks for your tip, How I missed it after years ! But in my case after tried several Windows/Linux machines only `Space` go by page works.

>  the `clink-select-complete` command displays an interactive scrollable and filter-able list to choose from

Indeed it's a nice thing to have.

> These all seem like even more functional and convenient solutions than removing the recursive list. Do any of these alternatives seem helpful

After all your suggestions I think it's enough for my work, no need to add option to remove recursion at the moment.

**Comment by chrisant996** [comment]
> > In the pager, Enter goes by line, Space or Tab go by page, and d goes by half-page.
> 
> Thanks for your tip, How I missed it after years ! But in my case after tried several Windows/Linux machines only `Space` go by page works.

The keys I listed are for Clink.

In bash Space or Y print another page, and Enter print another line.

I added a to-do item in Clink to explore feasibility of supporting external pagers like `less`.  If you want to suggest that engagement in bash, contact the bash project and submit the suggestion there.

And I'll add `?` to print help in the pager prompt.

> After all your suggestions I think it's enough for my work, no need to add option to remove recursion at the moment.

Ok.  If you identify other tweaks or adjustments that could further improve the experience, please let me know.

**Comment by chrisant996** [comment]
> The keys I listed are for Clink.

Doh!  But while making an improvement a while ago, I accidentally disabled the Clink completion-pager enhancements.

I'm re-activating them.  😳
