### ISSUE TITLE
Update docs

### ISSUE THREAD

**Issue by IlyaKalosha** [vladimir-kotikov/clink-completions#185]
Please add Readme section on how to update clink-completions

**Comment by chrisant996** [comment]
Ok.

It's just "unzip the .zip file into whatever directory you already have the files".

Do you use Cmder?  I can see how Cmder users might wonder how, since it comes with Cmder.

I wonder if it belongs in the Cmder docs.

**Comment by chrisant996** [comment]
See https://github.com/vladimir-kotikov/clink-completions#installation-and-updates.
