### ISSUE TITLE
Completions for git aliases

### ISSUE THREAD

**Issue by narnaud** [vladimir-kotikov/clink-completions#188]
It would be nice to have completions also for git aliases, when possible.

For example, I have an alias `del = branch -D` to delete a branch, when I type: `git del <Tab>` I would expect to see the list of branches.
If I type `git branch -D <Tab>`, it's working as expected.

**Comment by chrisant996** [comment]
Alias support already exists, and does completion for flags.

But apparently there is a bug and it doesn't do completion properly for non-flags.

I'll dig into it.

**Comment by chrisant996** [comment]
@narnaud what version of clink-completions are you using?

Support for aliases was added in v0.4.0, published on August 25, 2022 (the original commit was 292814ea9841906303807dd4b4c535d19938847b).

Did you create a new alias and immediately try to do completions with it?  You would need to reload Clink via <kbd>Ctrl</kbd>-<kbd>X</kbd>,<kbd>Ctrl</kbd>-<kbd>R</kbd> to reload the git argmatcher and pick up the new aliases.

**Comment by chrisant996** [comment]
Oh, I see.  You have an alias _which includes flags_.  That's a whole other complicated problem.

There isn't a way to support that at this time.  It's too sophisticated for Clink's argmatcher system, sorry.  I'll add it to the wish list for future changes in Clink, and maybe it can happen someday.

**Comment by narnaud** [comment]
@chrisant996 Thank you for looking at that. For the records, I'm using the latest clink and clink-completions from scoop.

One way to mitigate the issue without doing too many changes and refactoring would be to provide a way for defining how a command completion should behave: ie `git del` (my alias) should complete like `git switch`.
But it may be too specific to spend time on it...

In the meantime, I've added a branch viewer with fzf where I can delete local branches... so it's less an issue for me.

Thanks for the work, love clink!

**Comment by chrisant996** [comment]
Update:  As of last night, I have some prototype changes in Clink and clink-completions that seem to be working for the "branch -D" example.

I don't have an ETA, though -- there is still much testing and validation to be done.
And I plan to support the `!` syntax, but I haven't started on that part yet.

**Comment by chrisant996** [comment]
Update:

- The https://github.com/chrisant996/clink/tree/argmatcher_onalias branch has the Clink side of the changes.
- The https://github.com/vladimir-kotikov/clink-completions changes have been published, but they have no effect unless running inside Clink v1.6.18 or higher (which isn't released yet).

I still need to address a couple quirks, write tests, and write documentation.

Once I'm satisfied, then I'll publish the Clink update, and the clink-completions side will automatically start working as well.

**Comment by chrisant996** [comment]
Clink v1.6.18 has been published.

After updating both Clink and clink-completions, git aliases should work very well.
