### ISSUE TITLE
autocomplete remote branches

### ISSUE THREAD

**Issue by albfan** [vladimir-kotikov/clink-completions#22]
In this WIP

https://github.com/albfan/clink-completions/commit/d48adfbffed3dc5909a5a93d20e4ee0622efa8a2

I found that clink divides autocompletion on "/".

    $ git rebase <TAB>
    origin/master origin/wip vladimir/master vladimir/extended vladimir/dev master wip
    $ git rebase o<TAB>
    $ git rebase origin/<TAB>
    -- no output --

and it do not offer autocompletion

When there is only one branch on remote autocompletion works.

Is there any solution to avoid stop on "/"? I've tried "disable_file_matching()" but didn't solve it.

**Comment by vladimir-kotikov** [comment]
Hmm... This may be related to how clink arguments framework works with `/` symbol. AFAIK it treats such symbol as a flag indicator (along with dash `-`). Need to double check...

**Comment by albfan** [comment]
You are right:

https://github.com/mridgers/clink/blob/master/clink/lua/arguments.lua#L76

Since "\" is the dir separator on windows, seems correct to interpret "/" as flag. I must propose a fix or tweak for this on clink.

**Comment by albfan** [comment]
I couldn't solve by myself (I'm newbie to lua)

https://github.com/mridgers/clink/issues/327

but almost... hope you can finish it or point how.

**Comment by albfan** [comment]
Finally it was only a match problem:

    $ git diff <TAB>
    origin/master origin/extended master
    $ git diff o<TAB>
    $ git diff origin/
    origin/master origin/extended
    
at this point, token is "origin/" and that did not match any remote. Once solved autocomplete works on remote branches
