### ISSUE TITLE
autocomplete on git aliases

### ISSUE THREAD

**Issue by albfan** [vladimir-kotikov/clink-completions#24]
When you define something like

```
$ git config alias.ci commit
```

you can issue 

```
$ git ci -m "whatever"
```

To do a commit

Is expected that you can autocomplete on this shorcuts

Technical doc:

https://git.wiki.kernel.org/index.php/Aliases

**Comment by lijunle** [comment]
This function does not work in my box. :(

```
C:\Users\lijunle\Repos\test>git config --get-regexp alias 2>nul
alias.st status -sb
alias.ci commit
alias.br branch
alias.co checkout
alias.ft fetch -p
alias.cp cherry-pick
```

**Comment by vladimir-kotikov** [comment]
@lijunle, thanks for report. i'll investigate

**Comment by albfan** [comment]
This only adds autocompletion for alias itsef.

But the fix is easy, just need some boilerplate code. The match from alias an real command should be keeped, and the parser should be added to aliases based on its real command.

comments on code review

**Comment by vladimir-kotikov** [comment]
> This only adds autocompletion for alias itsef

@albfan, yep, i did get sorted. I think it's possible to get completions for aliased commands by making `aliases` function returning parsers from `git_parser`, This would allow to not restructure the whole `git_parser` as this would be very massive change. I'll take a look at this approach in the mean time

**Comment by glucas** [comment]
As a workaround or short-term solution, Is there a way users can add their own aliases to the git_parser, without modifying git.lua directly? I'm not that familiar with the clink api, so wondering if I could do something along the lines of write my own lua file that gets the current git_parser and adds additional commands?

**Comment by Dji75** [comment]
Hello,
Is there any news about this enhancement ? :)

**Comment by Dji75** [comment]
@vladimir-kotikov are you still get involved in this project ?
As you seemed to say, the issue does not look so hard to fix, could we have some hope that it will be fixed soon ? ^_^

**Comment by albfan** [comment]
My relation with windows involves using msys2 and not reinvent the wheel.

**Comment by Dji75** [comment]
@albfan , you make my day !
I used [this link](https://zyzyz.github.io/en/2017/10/Integrate-MSYS2-into-Cmder/) in order to use msys2 with cmder and git bash completion works perfectly, many thanks !
