### ISSUE TITLE
Completions are broken with clink@0.4.4

### ISSUE THREAD

**Issue by vladimir-kotikov** [vladimir-kotikov/clink-completions#31]
See https://github.com/mridgers/clink/issues/358#issuecomment-148527725

> git subcommands aren't expanding for me 

with this: https://www.dropbox.com/sh/hqbrpkf0dpmmizq/gGX4XWAWIA

**Comment by vBm** [comment]
I've used `20150923_1abb57` dev build but that didn't help me.
There's still an issue when trying to do `git add x`

**Comment by vladimir-kotikov** [comment]
@vBm, just checked the build you mentioned, all works fine with current master. The issue with `git add` was fixed in https://github.com/vladimir-kotikov/clink-completions/commit/d2ac83817a329b02e1deca6fa6f59f15ec7c84f5

Closing this, please reopen if you still have any problems.

**Comment by vBm** [comment]
@vladimir-kotikov thanks, that commit indeed fixed the issue.
Thanks again.
