### ISSUE TITLE
Complete remote branches for `git checkout`

### ISSUE THREAD

**Issue by Toxaris** [vladimir-kotikov/clink-completions#35]
If there's a remote branch `origin/foo` but no local branch `foo`, then `git checkout foo` automatically sets up a new local branch `foo` that tracks `origin/foo`. Currently, the completion `foo` is not picked up because the name of the existing branch is `origin/foo`, not `foo`. I would be nice to get completion for the `foo` in such situations.

**Comment by vladimir-kotikov** [comment]
@Toxaris, could you please try this out?

**Comment by vladimir-kotikov** [comment]
Argh, ctrl+enter reopened the issue :angry:

**Comment by Toxaris** [comment]
:+1: looks great.

Maybe except that it appears as if some branch names can show up more than once in the completion list. For example, if there's `master` and `origin/master`, I seem to get two `master` entries in the completion list. I don't know whether that's to be expected or not.

**Comment by vladimir-kotikov** [comment]
Thanks for testing :)

No, this is not expected, I’ll try to look where the problem is.
