### ISSUE TITLE
Git completions don't work for submodules

### ISSUE THREAD

**Issue by gpakosz** [vladimir-kotikov/clink-completions#46]
Git completions seem to rely on finding the git-dir as per https://github.com/vladimir-kotikov/clink-completions/blob/e2467f6e57e5195d7c8c75f327121b1568f09a7d/git.lua#L14-L30

However, since Git 1.7.8, submodules don't contain a .git/ folder anymore.
Instead, the submodule directory is populated with a .git text file
which contains a git-dir: /path/to/superproject/git_dir/modules/name.

See: https://github.com/git/git/blob/master/Documentation/RelNotes/1.7.8.txt#L109-L114

It believe that changing the implementation of `get_git_dir()` to make it parse the `git-dir` value from the `.git` text file will solve the issue. I would have offered a PR right now if I was more familiar with the Lua syntax :)

**Comment by vladimir-kotikov** [comment]
@gpakosz, could you check if https://github.com/vladimir-kotikov/clink-completions/commit/a14af9c775734397b6c18210cbde5776103ff8ba works for you?

**Comment by gpakosz** [comment]
It seems it works for me.

Contrary to what my first read of `cmder`'s source code made me state, cmderdev/cmder#833 won't be automatically fixed when this issue is fixed though.

An equivalent `get_git_dir()` function has to be implemented in `cmder`'s `clink.lua`

**Comment by vladimir-kotikov** [comment]
Closing as resolved. @gpakosz, let's continue discussion on cmderdev/cmder#833
