### ISSUE TITLE
Git prompt example?

### ISSUE THREAD

**Issue by idvorkin** [vladimir-kotikov/clink-completions#49]
Is anyone using a git prompt, something that shows current branch etc? If so, can you share it so I can copy/modify :)

**Comment by vladimir-kotikov** [comment]
Not sure if i can get your question. If you need an example of how to deal with git prompt within clink, you'd better check out how Cmder does that: https://github.com/cmderdev/cmder/blob/development/vendor/clink.lua#L141-L168

**Comment by idvorkin** [comment]
Yup, that's what I'm looking for - thanks!

**Comment by idvorkin** [comment]
FYI - conemu supports showing git command line via: 

   gitshowbranch /i

**Comment by vladimir-kotikov** [comment]
I see. I think this is because `gitshowbranch.cmd` calls the real `git` process, which is MUCH slower than reading one file from git directory.
