### ISSUE TITLE
clink-completions/vagrant.lua:66

### ISSUE THREAD

**Issue by aaroncalderon** [vladimir-kotikov/clink-completions#56]
I installed `cmdr` which hapens to use your clink-completions. I stumbled upon this error, where we get the following message when a console starts.

> .../vendor/clink-completions/vagrant.lua:66: Additional arguments to new_parser() must be tables or strings

This issue has been reported on [cmdr issue #779](https://github.com/cmderdev/cmder/issues/779#issuecomment-228819072), but no real fix has been found.

Currently I have commented out line 66 to have the message go away, but I'm missing the intended functionality. 

I have tryed to troublesoot the issue, but was not able to figure it out. So, I just want to report the issue so you are ware of it.

Thanks.

**Comment by tonidy** [comment]
@aaroncalderon you can use this work around #53 until it merged to repo

**Comment by aaroncalderon** [comment]
@tonidy Thanks for the reply. Will try that as soon as I can.
