### ISSUE TITLE
npm.lua `package.json` Package_name and Package_version shows twice

### ISSUE THREAD

**Issue by aaroncalderon** [vladimir-kotikov/clink-completions#57]
At file line [npm.lua#214](https://github.com/vladimir-kotikov/clink-completions/blob/0.3.1/npm.lua#L214) seems that makes the output appear twice, I do not knwo if this is the intended behaviour

> C:\dev\github\app (rc-1.2.1) __(project@1.2.1)__ __(project@1.2.1)__

Note how the proje `(project@1.2.1)` shows twice.

**Comment by aaroncalderon** [comment]
The duplication happens on the command line. Like the example I provided if you go to the path `C:\dev\github\app` and that path is a git repository, then it shows like:

> C:\dev\github\app (rc-1.2.1) __(project@1.2.1)__ __(project@1.2.1)__

or maybe, if you are on the branch `master`

> C:\dev\github\app (master) __(project@1.2.1)__ __(project@1.2.1)__

It shows the project name (__projec__) and version (1.2.1) twice like

> __(project@1.2.1)__

at the end of the line. Unless this only happens on my cmdr command prompt.

**Comment by vladimir-kotikov** [comment]
@aaroncalderon, this doesn't repro for me. Could you please give exact versions of clink and Cmder, you're using.

**Comment by aaroncalderon** [comment]
Using

- cmder v 1.3
- ConEMu 160207 [32]
- Clink v0.4.7 [git:dfc95a]
- clink-completions v 0.3.1 From GitHub

  > I'm not using the version bundled with cmdr, I downloaded the version from GitHub

![duplicatenpmversion](https://cloud.githubusercontent.com/assets/14810269/16887301/cec07cf0-4a9e-11e6-95ed-02f0a003e9c9.png)

**Comment by aaroncalderon** [comment]
I just tryed cmdr v 1.3.0 and the issue seems to be fixed.

Version overview
- cmder v 1.3.
- ConEMu 160207 [32]
- Clink v0.4.8 [git:d565ad]
- link-completions v 0.3.1 (bundeled version)

Seems the only difference was __Clink__, I do not know if that was the problem then.
