### ISSUE TITLE
Typo?

### ISSUE THREAD

**Issue by Stanzilla** [vladimir-kotikov/clink-completions#58]
I haven't checked but this looks like a typo to me https://github.com/vladimir-kotikov/clink-completions/blob/master/git.lua#L825 a few lines down again, too.

**Comment by vladimir-kotikov** [comment]
Hmm... Just checked and it doesn't seem to be. Take a look at [man page](https://git-scm.com/docs/git-svn) and search for `svm` term

**Comment by Stanzilla** [comment]
weird! all good then :)
