### ISSUE TITLE
Add completions for `gh` (GitHub.cli)

### ISSUE THREAD

**Issue by vladimir-kotikov** [vladimir-kotikov/clink-completions#59]
**hub** is a command-line wrapper for git that makes you better at GitHub. See https://hub.github.com for CLI examples

**Comment by chrisant996** [comment]
`hub` is deprecated and replaced by [`gh`](https://github.com/cli/cli).  I'll explore cost/feasibility of adding completions for `gh`.

**Comment by eggbean** [comment]
I came here hoping to find a `gh` completion file for clink. I tried getting a lua specialised GPT to translate the zsh _gh file into lua, but it said that it was too complicated.

**Comment by chrisant996** [comment]
I have a prototype script for `gh` completions.  I haven't had time to test it or fill in the gaps.

Would you like to mess around with testing it and filling in stuff, or at least filing issues for what's missing or wrong?

I can make a topic branch for working on the `gh` completions, if you'd like.

**Comment by chrisant996** [comment]
I created a [gh_completions](https://github.com/vladimir-kotikov/clink-completions/tree/gh_completions) topic branch.

It has [gh.lua](https://github.com/vladimir-kotikov/clink-completions/blob/gh_completions/completions/gh.lua) which is the prototype script.

**Comment by eggbean** [comment]
> Would you like to mess around with testing it and filling in stuff, or at least filing issues for what's missing or wrong?

Sure. I'll start using it and see if I come across any problems.

**Comment by chrisant996** [comment]
@eggbean How have the `gh` completions been working for you?  Any feedback, things to fix or improve?

**Comment by eggbean** [comment]
Yes, it's bee working well for me. I haven't tried subcommand extensively, but I have been using a few subcommands that I had never used before, as I didn't know they even existed until using these completions.

(I still haven't been able to combine these completion suggestions with the repeated tab cycling, in a similar way that is possible in zsh, though)

**Comment by chrisant996** [comment]
> (I still haven't been able to combine these completion suggestions with the repeated tab cycling, in a similar way that is possible in zsh, though)

Can you give an example?

**Comment by chrisant996** [comment]
> (I still haven't been able to combine these completion suggestions with the repeated tab cycling, in a similar way that is possible in zsh, though)

@eggbean I don't understand what is meant by that.  Can you give an example?  I can probably explain or show how.

**Comment by eggbean** [comment]
Sorry, I'll get back to you soon once I figure out what I meant.

**Comment by chrisant996** [comment]
> (I still haven't been able to combine these completion suggestions with the repeated tab cycling, in a similar way that is possible in zsh, though)

@eggbean Maybe you meant one of these?
- Do you want the dark gray "auto suggestion" text to only show suggestions from available completions and never from history?  `clink set autosuggest.strategy match` (that would be pretty non-useful though; it might be better to just turn off autosuggest entirely in that case).
- Do you want <kbd>Tab</kbd> to cycle through completions?  Either set Clink to use Windows key bindings instead of Bash key bindings (`clink set clink.default_bindings windows`) or set up bindings in your `.inputrc` file such as:
  ```inputrc
  "\C-I":    old-menu-complete
  "\e[Z":    old-menu-complete-backward
  ```

**Comment by chrisant996** [comment]
@eggbean Or I think <kbd>Tab</kbd> in `zsh` by default behaves like the `menu-complete` command.  So these key bindings instead:
```inputrc
"\C-I":    menu-complete
"\e[Z":    menu-complete-backward
```

But trying to figure out what you're referring to led me to find that in Clink the `menu-complete` command wasn't updated to respect the `completion-auto-query-items` config variable.  So a fix for that is coming in v1.6.14 (probably in a week or two).

**Comment by chrisant996** [comment]
@eggbean I think that the outstanding issue about "combine these completion suggestions with the repeated tab cycling, in a similar way that is possible in zsh" is not about the `gh` argmatcher, and is instead about how to configure the tab completion command(s) to behave similarly to `zsh` for all completion in general.

I'm going to go ahead and publish a new release for the clink-completions repo.

**Comment by chrisant996** [comment]
Completions for `gh` were added in commit 651b979b4b07f3c4ecb104fdb0209f8a3b39d807.

**Comment by eggbean** [comment]
Hi, sorry I've been away from this for a few months. I'm trying to get familiar with everything again. When I try tab completing anything for the first time I get this error. Subsequent attempts just returns the last line:

```
jason@hyperion:~\winfiles\scripts> gh
loading completion script failed:
...n\winfiles\Settings\clink-completions\completions\gh.lua:9: module 'clink_version' not found:
        no field package.preload['clink_version']
        no file 'C:\WINDOWS\System32\lua\clink_version.lua'
        no file 'C:\WINDOWS\System32\lua\clink_version\init.lua'
        no file 'C:\WINDOWS\System32\clink_version.lua'
        no file 'C:\WINDOWS\System32\clink_version\init.lua'
        no file '.\clink_version.lua'
        no file 'C:\WINDOWS\System32\clink_version.dll'
        no file 'C:\WINDOWS\System32\loadall.dll'
        no file '.\clink_version.dll'
stack traceback:
        ...n\winfiles\Settings\clink-completions\completions\gh.lua:9: in function 'func'
        ~clink~/lib/arguments.lua:2456: in function <~clink~/lib/arguments.lua:2451>
        [C]: in function 'xpcall'
        ~clink~/lib/arguments.lua:2458: in function 'attempt_load_argmatcher'
        ~clink~/lib/arguments.lua:2505: in function '_has_argmatcher'
        ~clink~/lib/arguments.lua:2588: in function '_find_argmatcher'
        ~clink~/lib/arguments.lua:2862: in function 'classify'
        ~clink~/lib/classifier.lua:78: in function <~clink~/lib/classifier.lua:71>
        [C]: in function 'xpcall'
        ~clink~/lib/classifier.lua:93: in function <~clink~/lib/classifier.lua:70>
.exe
can't execute 'fzf_complete'; not a function
```

For the last line, I tried replacing `fzf_complete` with `fzf_tab` in my `_inputrc` as it looked like the change you have made, but it didn't fix the problem.

**Comment by chrisant996** [comment]
The error message looks like you created a brand new installation of clink-completions, but you only installed some of the files/directories.  You have to install all of them, and they have to be in a directory that's in Clink's script path.  Also, don't rearrange which subdirectories files are in.

1. Check that you've installed of the files.
2. Check that they're in a directory that's listed next to "script paths:" in the output from `clink info`.

Check the [Installation and Updates](https://github.com/vladimir-kotikov/clink-completions#installation-and-updates) section of the readme.md file for details.

Specifically, it looks like you're missing the `modules\` subdirectory and/or the `!init.lua` file.
