### ISSUE TITLE
clink/clink.lua:897: Tables can't have meta-tables.

### ISSUE THREAD

**Issue by AbhishekTripathi** [vladimir-kotikov/clink-completions#6]
I am trying to use your most recent version of git.lua with the latest clink (0.4.2). I keep getting following error -

Clink v0.4.2 [git:1111eb] Copyright (c) 2014 Martin Ridgers
http://mridgers.github.io/clink
D:\Apps\cmder\vendor\clink-new/clink.lua:897: Tables can't have meta-tables.

I see that clink is updated as per your suggestions for config file. I also verified that the error is displayed only when I use newer version of git.lua. I have an old version from cmder and it doesn't yield error but is way too limited. Thanks a ton for investing your time in writing these useful scripts. I would request you to distribute most recent compatible version of clink too along with your extensions to avoid compatibility issues.

**Comment by vladimir-kotikov** [comment]
Works with clink@0.4.3
