### ISSUE TITLE
Request for npm install

### ISSUE THREAD

**Issue by Seb-** [vladimir-kotikov/clink-completions#60]
Hello,

I would like to request autocomple for `npm install` (suggesting packages) like it does from `npm remove`.

Thank you!

**Comment by busches** [comment]
`npm remove` searches through the packages you have installed, an easy to access number. `npm install` would require searching the entire `npm` registry and any others you may define. I don't believe this is feasible.

**Comment by vladimir-kotikov** [comment]
Yeah, right. It might be possible to offer a limited set of completions based on local NPM cache, but I don't feel that this is right thing to do. I'd better to not provide any completions rather than give users a very limited workaround.
