### ISSUE TITLE
Support click (Python command line library) completions

### ISSUE THREAD

**Issue by elnuno** [vladimir-kotikov/clink-completions#81]
[Click](http://click.pocoo.org/6/) is "a Python package for creating beautiful command line interfaces in a composable way with as little code as necessary". There is a [click-completion](https://github.com/click-contrib/click-completion) project that provides support for automagically adding completion support to click-based apps (works with fish, Zsh, Bash and PowerShell so far). It would be totally rad if both could work together to get click completion on clink.

See click-contrib/click-completion#2.

**Comment by glehmann** [comment]
indeed, that would be interesting. We have no knowledge about clink or clink-completions though, so a little guidance on where to begin would be great!

More specifically, click-completion is working by generating a list of possible completions given the current command line being typed by the user. click-completion does not produce a complete set of available arguments or options that can be completed by another tool.
Is it possible to integrate this kind of behavior with clink/click-completions?

**Comment by glehmann** [comment]
BTW, I'm one of the click-completion developers

**Comment by elnuno** [comment]
I think it's possible, we'd need to create a Lua script that has more or less the same behavior the other ones have. I can try to write a quick and dirty one later this week.

**Comment by chrisant996** [comment]
Is there still interest in this?  I can help.
