### ISSUE TITLE
ssh completion does not work

### ISSUE THREAD

**Issue by lijunkang** [vladimir-kotikov/clink-completions#84]
ssh completion is broken for me. However, it works if I reverted `ssh.lua` file from 26f4f99fd4c010bee57c4b64b93b9f7171c4d978.

**Comment by vladimir-kotikov** [comment]
Hey, @lijunkang. Thanks for reporting the issue. Unfortunately I'm not actively maintaining this project anymore and don't have much time to contribute bugfixes, so if you have an idea how to fix this problem - PRs are welcome :)
