### ISSUE TITLE
Support git worktrees

### ISSUE THREAD

**Issue by fcharron** [vladimir-kotikov/clink-completions#94]
At the moment, `gitutils.get_git_dir.has_git_file()` returns an incorrect value when in a git worktree. In that situation, the content of the .git file follows the following scheme:
main repo -> c:/source/mainRepo
worktree -> c:/source/childWorktree
contents of c:/source/childWorktree/.git file -> `gitdir: c:/source/mainRepo/.git/worktrees/childWorktree`

In that situation, `has_git_file("c:/source/childWorktree")` returns `c:/source/childWorktree/c:/source/mainRepo/.git/worktrees/childWorktree`, which is incorrect.

ref: [git worktree doc](https://git-scm.com/docs/git-worktree)

**Comment by vladimir-kotikov** [comment]
@fcharron, #95 should fix it but unfortunately I can't test it because I don't have Windows machine at hand. May I ask you to try it out first before I merge it?

**Comment by fcharron** [comment]
@vladimir-kotikov Thanks for the quick fix! I tested it in cmder (I had to copy-paste the functions you modified at the right places in their config files) and it worked perfectly.

Once you merge, I will follow up with the cmder devs to integrate with them.

**Comment by vladimir-kotikov** [comment]
Cool, thanks for testing 👍

**Comment by vladimir-kotikov** [comment]
@fcharron FYI here is a PR with update: https://github.com/cmderdev/cmder/pull/1525
