### ISSUE TITLE
Add support for dotnet cli

### ISSUE THREAD

**Issue by jerkovicl** [vladimir-kotikov/clink-completions#99]
Is it possible to make a clink completions lua file for dotnet cli?

On official repo there are autocomplete scripts for powershell, bash and zsh:
[Powershell](https://github.com/dotnet/cli/blob/master/scripts/register-completions.ps1)
[Bash](https://github.com/dotnet/cli/blob/master/scripts/register-completions.bash)
[Zsh](https://github.com/dotnet/cli/blob/master/scripts/register-completions.zsh)

**Comment by SolWasserman** [comment]
https://github.com/vladimir-kotikov/clink-completions/pull/120
